server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/linkid+json

spring:
  application:
    name: linkid-resolver

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:linkid}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.linkgenetic.resolver: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

linkid:
  resolver:
    base-url: ${LINKID_BASE_URL:https://w3id.org/linkid}
    default-cache-ttl: 3600
    default-quality: 1.0
    default-language: en
    default-media-type: text/html
    fallback-resolvers:
      - https://backup.resolver.org/
      - https://archive.resolver.org/

    rate-limit:
      enabled: true
      requests-per-minute: 100
      requests-per-hour: 1000

    cache:
      enabled: true
      default-ttl: 3600
      max-entries: 100000

    security:
      require-auth: false
      jwt-secret: ${JWT_SECRET:change-me-in-production}
      jwt-expiration-hours: 24